---
abstract: 'pipemailer that changes plaintext to multi/alt with Markdown'
author:
  - ', Ricardo SIGNES.  This program is free software;  you can'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Smarkmail
name: App-Smarkmail
no_index:
  directory:
    - inc
    - t
requires:
  Email::MIME: 0
  Email::MIME::Creator: 0
  Email::MIME::Modifier: 0
  Email::Sender: 0
  HTML::Entities: 0
  Text::Markdown: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjbs/app-smarkmail
version: 0.003
